name: scrolling_years_calendar
description: A calendar widget to easily scroll through the years, allowing for customizations to fit your design.
version: 1.3.1
homepage: https://github.com/mennorenkens/flutter_scrolling_calendar

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  infinite_scroll_pagination: 3.2.0
  infinite_listview: 1.1.0
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # BSD
  flutter_lints: 2.0.1
